Don Quixote and Sancho, mounted on a donkey, set out.
In their first adventure, Don Quixote mistakes a field of windmills for giants and attempts to fight them but finally concludes that a magician must have turned the giants into windmills.
He later attacks a group of monks, thinking that they have imprisoned a princess, and also does battle with a herd of sheep, among other adventures, almost all of which end with Don Quixote, Sancho, or both being beaten.
Eventually, Don Quixote acquires a metal washbasin from a barber, which he believes is a helmet once worn by a famous knight, and he later frees a group of convicted criminals.

Don Quixote subsequently encounters Cardenio, who lives like a wild man in the woods because he believes that Luscinda, the woman he loves, betrayed him.
Don Quixote decides to emulate him to prove his great love for Dulcinea, and he sends Sancho to deliver a letter to her.
When Sancho stops at an inn, he finds two of Don Quixote’s old friends, a priest and a barber, looking for him.
They decide that one of them should pose as a damsel in distress to try to lure Don Quixote home.
En route, they come across a young woman, Dorotea, who was betrayed by Don Fernando, who married Luscinda.
Dorotea agrees to pretend to be a princess whose kingdom has been seized by a giant, and Don Quixote is persuaded to help her.
They stop at the inn, where Don Fernando and Luscinda soon arrive.
Luscinda is reunited with Cardenio, and Don Fernando promises to marry Dorotea.
Later, the priest and the barber put Don Quixote in a wooden cage and persuade him that he is under an enchantment that will take him to Dulcinea.
Eventually, they return him home.
